=== dtinit/data-transfer-project/extensions/data-transfer/portability-data-transfer-generic/payload-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "apiVersion": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "description": "The inner payload, which contains data from one of the described data verticals"
    },
    "schemaSource": {
      "type": "string",
      "description": "The source file containing the schema definition"
    },
    "@type": {
      "const": "GenericPayload"
    }
  },
  "required": [
    "@type",
    "schemaSource",
    "apiVersion",
    "payload"
  ]
}

=== dtinit/data-transfer-project/extensions/data-transfer/portability-data-transfer-generic/social-post-payload-example.json
{
  "@type": "GenericPayload",
  "schemaSource": ".../SocialPostsSerializer.java",
  "apiVersion": "0.1.0",
  "payload": {
    "@type": "SocialActivity",
    "metadata": {
      "@type": "SocialActivityMetadata",
      "actor": {
        "@type": "SocialActivityActor",
        "id": "321",
        "name": "Steve",
        "url": "http://example.org/actor/321"
      }
    },
    "activity": {
      "@type": "SocialActivityModel",
      "id": "456",
      "published": "1731604863.845677",
      "type": "NOTE",
      "attachments": [
        {
          "@type": "SocialActivityAttachment",
          "type": "IMAGE",
          "url": "foo.com",
          "name": "Foo",
          "content": "Example content"
        }
      ],
      "location": {
        "@type": "SocialActivityLocation",
        "name": "foo",
        "longitude": 10.0,
        "latitude": 10.0
      },
      "title": "Hello world!",
      "content": "Hi there",
      "url": "http://example.org/post/foo"
    }
  }
}

=== dtinit/data-transfer-project/extensions/data-transfer/portability-data-transfer-generic/media-payload-example.json
{
  "@type": "GenericPayload",
  "schemaSource": ".../SocialPostsSerializer.java",
  "apiVersion": "0.1.0",
  "payload": {
    "@type": "SocialActivityData",
    "metadata": {
      "@type": "SocialActivityMetadata",
      "actor": {
        "@type": "SocialActivityActor",
        "id": "321",
        "name": "Steve",
        "url": null
      }
    },
    "activity": {
      "@type": "SocialActivityModel",
      "id": "456",
      "published": 1731604863.845677,
      "type": "NOTE",
      "attachments": [
        {
          "@type": "SocialActivityAttachment",
          "type": "IMAGE",
          "url": "foo.com",
          "name": "Foo",
          "content": null
        }
      ],
      "location": {
        "@type": "SocialActivityLocation",
        "name": "foo",
        "longitude": 10.0,
        "latitude": 10.0
      },
      "title": "Hello world!",
      "content": "Hi there",
      "url": null
    }
  }
}
